
server:
  port : 0

spring:
  application:
    name : user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url : jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

    #부트스트랩 대신에 이렇게 설정만 추가하면 됨. boot 2.4 이후 //유저서비스에서 config-server를 연결하는 정보
  config:
    import : optional:configserver:http://localhost:8888
  cloud:
    config:
      name : ecommerce
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
        #http://desktop-fhh3fja:60723/actuator/beans
        #http://desktop-fhh3fja:60723/actuator/health
        #http://desktop-fhh3fja:60723/actuator/refresh (git-local-repo 환경변수 변경 add commit, postman post왼쪽 주소, 변경된값 적용
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/test
#      connectionTimeout: 30000
#      maximumPoolSize: 10
#      maxLifetime: 1800000
#      poolName: HikariCP
#      readOnly: false
#      connectionTestQuery: SELECT 1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
 
logging:
  level:
    '[com.example.userservice]' : DEBUG
          
greeting:
  message: Welcome to the Simple E-commerce.
  
#token:
#  expiration_time: 86400000
#  secret: user_token
        
  
  